### ISSUE TITLE
`cpu/utilization` output parameter needs to be numeric instead of string type in "azure-importer" plug-in

### ISSUE THREAD

**Issue by pangteckchun** [Green-Software-Foundation/if-unofficial-plugins#76]
Hi, great work on  `azure-importer` plug-in.
I was able to get the outputs from it and i wanted to use some of the outputs with `teads-curve` plug-in.

Unfortunately, the `cpu/utilization` field is not numeric and the IF runs failed when `teads-curve` tries to consume the parameter. Stack trace:
```
[2024-04-21 02:28:05.685 PM] error:     "cpu/utilization" parameter is expected number, received string. Error code: invalid_type.
InputValidationError:   "cpu/utilization" parameter is expected number, received string. Error code: invalid_type.
    at validate (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\util\validations.js:48:15)
    at validateInput (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\teads-curve\index.js:130:43)
    at C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\teads-curve\index.js:24:31
    at Array.map (<anonymous>)
    at Object.execute (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\teads-curve\index.js:23:23)
    at computeNode (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\compute.js:57:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async traverse (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\compute.js:11:9)
    at async compute (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\compute.js:79:5)
    at async impactEngine (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\index.js:26:30)
```

I observed some of the outputs from `azure-importer` might need to be numeric instead of string for consistency, for `memory/capacity/GB` output parameter. Is there a reason they have to be in string?

Looking forward to your inputs. Abit stucked right now.

Thank you!
TC

**Comment by pangteckchun** [comment]
Hi Manushak, thank you for working on this fix. We see it is still pending review before merge. Any idea if this might be done soon?

Cheers
TC
