### ISSUE TITLE
*instance-type* value from `azure-importer` output plays well with `cloud-metadata` but not with `ccf` plug-in

### ISSUE THREAD

**Issue by pangteckchun** [Green-Software-Foundation/if-unofficial-plugins#79]
## Scope

What does your feedback relate to?

- [] Project aims/objectives
- [] Repository structure
- [X] Model plugin
- [] Rimpl code
- [] Documentation
- [] Tests
- [] Other

## Details
1. Using `azure-importer` output in *instance-type* which in my setup yields the value **Standard_DS1_v2** for an Azure VM.
2. This is tested as an input parameter to `cloud-metadata` and the output yields the correct processor information - all good!
```
vcpus-allocated: 1
vcpus-total: 64
memory-available: 3
physical-processor: >-
            Intel® Xeon® Platinum 8370C,Intel® Xeon® Platinum 8272CL,Intel®
            Xeon® 8171M 2.1 GHz,Intel® Xeon® E5-2673 v4 2.3 GHz,Intel® Xeon®
            E5-2673 v3 2.4 GHz
cpu/thermal-design-power: 270
```
3. Using the same *instance-type* value into `ccf` plug-in resulted in the following validation exception (gracefully handled and good error messages - thank you!):
```
[2024-04-22 05:47:32.582 PM] error:     CloudCarbonFootprint: Instance type Standard_DS1_v2 is not supported.
UnsupportedValueError:  CloudCarbonFootprint: Instance type Standard_DS1_v2 is not supported.
    at validateInstanceTypeForVendor (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\ccf\index.js:63:19)
    at zod_1.z.object.refine.message (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\ccf\index.js:92:13)
    at Object.refinement (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\node_modules\zod\lib\types.js:200:28)
    at executeRefinement (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\node_modules\zod\lib\types.js:3004:39)
    at ZodEffects._parse (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\node_modules\zod\lib\types.js:3024:17)
    at ZodEffects._parseSync (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\node_modules\zod\lib\types.js:129:29)
    at ZodEffects.safeParse (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\node_modules\zod\lib\types.js:159:29)
    at validate (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\util\validations.js:46:37)
    at validateInputWithConfig (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\ccf\index.js:97:43)
    at C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if-unofficial-plugins\build\lib\ccf\index.js:39:148
```
I am running on my local laptop for testing, connected to a Azure cloud hosting a single VM, using IF v0.31.

## Expected Behaviour

1. `ccf` expected *instance-type* values are not consistent with behavior of `cloud-metadata`.
2. What would be nice is `ccf` can use the same *instance-type* value as `cloud-metadata` and return the embodied carbon for the VM type.
3. This would remove unnecessary string parsing, say using `regex` plug-in to extract VM name to feed into `ccf`. String parsing can make the IF pipeline brittle if VM name changes over the course of operations.

## Actual behaviour

Per what was highlighted in **Details** step 3, `ccf` returns unsupported instance type for the VM we have used.
I wiill trying to regex to extract the words that might fit `ccf` azure instances supported VM names.

## Proposed actions

Proposed to align the instance-type values in `ccf` plug-in, for Azure VMs, with the same as `cloud-metadata` and `azure-importer`.

**Note: We will take all feedback seriously. Please be polite and constructive - aggressive or abusive feedback will simply be deleted.**

**Comment by jmcook1186** [comment]
Thanks for raising the issue - I'll take a look later today and get back to you.

**Comment by jmcook1186** [comment]
Hi - I looked into this issue a bit. 

The two plugins use different datasets that use different schema for their entries and the names don't match 1-1. For example, the cloud metadata plugin entry for your `Standard_DS1_v2` returns three possible processors in a single field in its metadata, whereas CCF has separate entries named DS1_v2 for each processor. So the lookup works a little differently between the plugins. 

Our CCF plugin is really only a light typescript wrapper over the CCF data, so we probably don't want to mess with it too much as it will deviate from the expectations of CCF users.

For now if you need both plugins to interact and there's a naming mismatch you'll have to add the `regex` plugin to adjust the name passed to CCF.

We'd be happy to see a PR with an improved solution, but we don't have the capacity to prioritize this at the moment.

**Comment by pangteckchun** [comment]
Hi Joseph,
Thank you for the quick turnaround and spending time on this issue. Really appreciate this!

Ok understood. For now we will explore inserting a `regex` plug-in step in the pipeline and take it from there.
I am closing this feedback for now.

Cheers!
TC
